name: cou_server2
description: The CoU game server, version 2.
version: 2.0.0
author: CoU Development Team

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  aqueduct: "^2.1.1"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
